### ISSUE TITLE
How about HexMap change to static

### ISSUE THREAD

**Issue by Las-Wonho** [utilForever/Civilizationpp#21]
HexMap은 유일한 전체 맵입니다. 따라서 대부분의 유닛은 HexMap 인스턴스에 접근을 해야 합니다. 그 이유는 자신이 있는 타일에 따라서 이동이나 효율이 달라지기 때문입니다. 그러나 유닛들이 모두 맵을 속성으로 갖고있는 것 보다는 static으로 만들어서 접근이 가능하게 하는 것이 어떻겠습니까?

**Comment by JunHo-Seo** [comment]
처음 해당 코드 작성시에는 맵 생성 방식(ex: HexMap 클래스에서 직접 맵을 생성할 것인지 전용 클래스를 둘 것인니)이나 유닛 클래스에서 이 클래스를 어떻게 활용할 것인지에 대한 확신이 없어서 별다른 조치를 취하지 않았지만, 기초적인 유닛 클래스가 작성된 시점에서는 충분히 동의하는 사안입니다.

다만, 그렇다면 아예 HexMap 클래스를 싱글톤 구조로 변경하고, 생성자에 넘겨지는 인자는 generate 멤버 함수를 새로 생성해 이 함수로 옮기는 것이 좋아보이는데, HexMap 클래스를 싱글톤으로 바꾸는 것에 대해 어똫게 생각하시나요?

**Comment by Las-Wonho** [comment]
저는 싱글톤을 사용하는 것에 동의합니다.
