### ISSUE TITLE
Implement basic tile/tile set structure

### ISSUE THREAD

**Issue by utilForever** [utilForever/Civilizationpp#5]
This revision implements basic square/hexagonal tile-based grid, with the higher priority at implementing the hexagonal one. The planned-features are:

- HexagonalGrid implementation using different axis-models.
- Get specific tile using coordinates
- Get tiles adjacent to the specific tile

More features could be implemented, However, that's beyond the scope of it.

Reference: https://www.redblobgames.com/grids/hexagons/

**Comment by JunHo-Seo** [comment]
This revision implements basic square/hexagonal tile-based grid, with the higher priority at implementing the hexagonal one. The planned-features are:

- Hexagonal Grid implementation using different axis-models.
- Get specific tile using coordinates
- Get tiles adjacent to the specific tile

More features could be implemented, however, that's beyond the scope of it.

Ref.: https://www.redblobgames.com/grids/hexagons/
